### PR TITLE
Santize utf8 label values

### PR DESCRIPTION
**Pull request by tivvit**
using https://github.com/aerospike/aerospike-prometheus-exporter/pull/18

based on https://github.com/alicebob/asprom/pull/42 - there is a description of the problem and the used solution is very similar - in this project, there is no wrapper function for metrics so I had to add it to more places.

### CODE REVIEW

**Comment by khaf** [comment]
Can we please have this PR decoupled from the #18? At this moment that changeset cannot not be merged.

**Comment by tivvit** [comment]
Yes I will prepare it. I am used to using modules, therefore it was more comfortable for me to do it like this, sorry for that

**Comment by tivvit** [comment]
done @khaf

**Comment by khaf** [comment]
Thank you, this is now much more clear to me. But I think there is no reason to pepper UTF8 validation all over the codebase.

There is a central function on the `Observer` that sends the requests to the server node and gets the result back. Those result are then sent to watchers to be parsed and used. That function stands in for the wrapper you are looking for.

You can add validations only in [`Observer.requestInfo`#L205](https://github.com/aerospike/aerospike-prometheus-exporter/blob/master/observer.go#L205) by ranging over `rawMetrics` map and validating the values:
```go
for range k, v := range rawMetrics {
  rawMetrics[k] = sanitizeLabelValue(v)
}
```
Is that what are looking for?

**Comment by tivvit** [comment]
thanks for the tip, this your proposed solution is much better

**Comment by khaf** [comment]
OK I merged this PR, but ended up rebasing it due to conflict with the other PR. Thank you for your efforts.

**Pull request closed without merging**
