### PR TITLE
OPS-3949 add in clock skew stop writes to example in readme

### PR DESCRIPTION
**Pull request by ben-at-aerospike**

### CODE REVIEW

**Comment by spkesan** [comment]
Hi @ben-at-aerospike 
This is an example to configure metric whitelist.
The alert rules example are [in aerospike-monitoring repository](https://github.com/aerospike/aerospike-monitoring/blob/ffe897cc57ab2e4e8fb1425bd7f76e0eec3edfc7/config/prometheus/aerospike_rules.yml#L28-L35)
And we have an example for `clock_skew_stop_writes` flag

**Comment by mtendjou** [comment]
@spkesan , @ben-at-aerospike confirmed in the associated Jira (OPS-3949). So if that is already taken care of, I guess you can close or check directly with Ben.

**Comment by spkesan** [comment]
@ben-at-aerospike 
I have added `clock_skew_stop_writes` to the grafana dashboards (`namespace view` as well as `cluster view`). That will go in with [aerospike/aerospike-monitoring PR20](https://github.com/aerospike/aerospike-monitoring/pull/20). Alert rule for `clock_skew_stop_writes` is already there.

So, I think this PR can be closed? Let me know. Thanks.

**Comment by spkesan** [comment]
@ben-at-aerospike 
I'll close this PR. Feel free to reopen this PR or let me know if you wanted to make any other change.

**Pull request closed without merging**
