### PR TITLE
[TOOLS-2090] fix: remove redundant decoding and re-encoding of cert

### PR DESCRIPTION
**Pull request by jdogmcsteezy**

### CODE REVIEW

**Comment by spkesan** [comment]
@dwelch-spike Can you validate this?
I was expecting it to work even with chain certificates.

**Comment by jdogmcsteezy** [comment]
@spkesan, I tested and validated the fix.  `pem.Decode(certFileBytes)` only grabs a single cert out of the certificate chain.  This method needs to be called in a loop to decode the entire chain.

**Comment by dwelch-spike** [comment]
@spkesan I have not reproduced this failure but @jdogmcsteezy has. The docs for decode to mention it doing one block at a time. https://pkg.go.dev/encoding/pem#Decode

**Review by dwelch-spike — APPROVED** [review]
LGTM but will wait to merge until @spkesan has a chance to see the new comments.

**Review by spkesan — APPROVED** [review]
Alright! Approved.

**Comment by spkesan** [comment]
We don't need to loop over to decode the entire set of pem blocks. The subsequent call to `tls.X509KeyPair()` will do it as well. So, we are good. Thanks @jdogmcsteezy for fixing this.

**Pull request merged**
